Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "forwarded_port", guest: 80, host: 8080

  #config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provision "ansible_local" do |ansible|
    ansible.become = true
    ansible.become_user = "root"
    ansible.compatibility_mode = "2.0"
    ansible.limit = "all"
    ansible.playbook = "playbook.yml"
  end
end
