Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_version = "1803.01"
  #config.vm.network "private_network", type: "dhcp"
  #config.vm.synced_folder ".", "/vagrant", type: "nfs"
end
